[package]
name = "tests"
version = "0.1.0"
description = "Created with Anchor"
edition = "2021"
rust-version = "1.89.0"

[dependencies]
anchor-client = "1.1.2"
agent-policy = { version = "0.1.0", path = "../programs/agent-policy" }
solana-keypair = "3.0.0"
solana-pubkey = "3.0.0"
solana-sdk-ids = "3"
solana-signer = "3"
